import { Tour, Destination, Testimonial } from "@/types";

export const tours: Tour[] = [
    {
        id: 1,
        slug: "raja-ampat-paradise",
        title: "Raja Ampat Paradise",
        location: "Papua Barat, Indonesia",
        duration: "7 Days",
        rating: 4.9,
        reviews: 128,
        price: 8500000,
        originalPrice: 10000000,
        image: "https://images.unsplash.com/photo-1596402184320-417e7178b2cd?w=800&q=80",
        gallery: [
            "https://images.unsplash.com/photo-1596402184320-417e7178b2cd?w=800&q=80",
            "https://images.unsplash.com/photo-1580541832626-2a7131ee809f?w=800&q=80",
            "https://images.unsplash.com/photo-1583212292454-1fe6229603b7?w=800&q=80",
        ],
        category: "Beach",
        badge: "Terpopuler",
        includes: ["Hotel", "Semua Makan", "Guide", "Snorkeling", "Speedboat"],
        maxPax: 12,
        minAge: 8,
        description:
            "Nikmati keindahan Raja Ampat yang luar biasa dalam paket wisata komprehensif ini. Jelajahi pulau-pulau tropis eksotis, selami lautan biru jernih penuh terumbu karang, dan rasakan keramahan warga lokal.",
        itinerary: [
            { day: 1, title: "Tiba di Sorong & Transfer", description: "Disambut guide kami di Bandara Domine Eduard Osok, transfer ke resort di Raja Ampat." },
            { day: 2, title: "Snorkeling Chicken Island", description: "Menikmati keindahan terumbu karang berwarna-warni dan ikan-ikan tropis." },
            { day: 3, title: "Pianemo & Friwen Wall Diving", description: "Sunrise di Pianemo, diving di Friwen Wall, BBQ malam hari di tepi pantai." },
            { day: 4, title: "Cape Kri & Manta Sandy", description: "Berenang bersama manta ray, snorkeling di Cape Kri." },
            { day: 5, title: "Wayag Lagoon", description: "Full day trip ke Wayag, trekking ke puncak untuk foto ikonik." },
            { day: 6, title: "Free Program & Sunset Cruise", description: "Aktivitas pilihan: kayak, snorkeling, atau relaxasi. Sunset cruise sore hari." },
            { day: 7, title: "Check-out & Pulang", description: "Sarapan, packing, transfer ke Sorong, penerbangan pulang." },
        ],
        island: "Papua",
    },
    {
        id: 2,
        slug: "bali-complete-experience",
        title: "Bali Complete Experience",
        location: "Bali, Indonesia",
        duration: "5 Days",
        rating: 4.8,
        reviews: 215,
        price: 5200000,
        originalPrice: 6500000,
        image: "https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=800&q=80",
        gallery: [
            "https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=800&q=80",
            "https://images.unsplash.com/photo-1518548419970-58e3b4079ab2?w=800&q=80",
        ],
        category: "Culture",
        badge: "Hot Deal",
        includes: ["Villa Private", "Semua Makan", "Guide", "Transport", "Spa"],
        maxPax: 20,
        minAge: 0,
        description: "Paket lengkap menikmati Bali dari budaya hingga alam. Villa private, pura-pura ikonik, sawah Tegalalang, dan sunset Uluwatu.",
        itinerary: [
            { day: 1, title: "Tiba di Bali & Check-in Villa", description: "Transfer ke villa, welcome dinner dengan pemandangan sawah." },
            { day: 2, title: "Ubud Cultural Tour", description: "Tegalalang Rice Terrace, Monkey Forest, Tirta Empul." },
            { day: 3, title: "Spiritual Bali", description: "Pura Besakih, Kintamani, Danau Batur, Penelokan." },
            { day: 4, title: "Nusa Penida Day Trip", description: "Kelingking Beach, Angel Billabong, Crystal Bay snorkeling." },
            { day: 5, title: "Free & Departing", description: "Shopping di Seminyak, sunset Uluwatu, transfer bandara." },
        ],
        island: "Bali",
    },
    {
        id: 3,
        slug: "bromo-sunrise-trekking",
        title: "Bromo Sunrise Trekking",
        location: "Jawa Timur, Indonesia",
        duration: "2 Days",
        rating: 4.7,
        reviews: 189,
        price: 1800000,
        image: "https://images.unsplash.com/photo-1622185135505-2d795003994a?w=800&q=80",
        gallery: ["https://images.unsplash.com/photo-1622185135505-2d795003994a?w=800&q=80"],
        category: "Adventure",
        badge: "Popular",
        includes: ["Hotel", "Sarapan", "Guide", "Jeep 4WD", "Masker"],
        maxPax: 8,
        minAge: 10,
        description: "Saksikan sunrise spektakuler dari puncak kaldera Bromo. Trekking di lautan pasir, foto ikonik, pengalaman yang tak terlupakan.",
        itinerary: [
            { day: 1, title: "Malang/Surabaya → Cemoro Lawang", description: "Perjalanan sore hari, check-in hotel, persiapan sunrise." },
            { day: 2, title: "Sunrise & Bromo Crater", description: "Bangun 03:00, jeep ke Penanjakan, sunrise view, turun ke kawah Bromo." },
        ],
        island: "Jawa",
    },
    {
        id: 4,
        slug: "yogyakarta-cultural",
        title: "Yogyakarta Cultural Tour",
        location: "DIY Yogyakarta, Indonesia",
        duration: "3 Days",
        rating: 4.6,
        reviews: 97,
        price: 2400000,
        image: "https://images.unsplash.com/photo-1584810359583-96fc3448beaa?w=800&q=80",
        gallery: ["https://images.unsplash.com/photo-1584810359583-96fc3448beaa?w=800&q=80"],
        category: "Culture",
        badge: "",
        includes: ["Hotel", "Makan", "Guide", "Transport", "Tiket Masuk"],
        maxPax: 15,
        minAge: 0,
        description: "Jelajahi Yogyakarta: Borobudur megah, Prambanan agung, Kraton, Malioboro, dan petualangan Merapi.",
        itinerary: [
            { day: 1, title: "Tiba & Malioboro", description: "Check-in, sore jalan-jalan Malioboro, makan gudeg." },
            { day: 2, title: "Borobudur & Prambanan", description: "Sunrise Borobudur, siang Prambanan, sore Kraton." },
            { day: 3, title: "Merapi Lava Tour", description: "Jeep Merapi lava tour pagi, siang check-out." },
        ],
        island: "Jawa",
    },
    {
        id: 5,
        slug: "komodo-island-adventure",
        title: "Komodo Island Adventure",
        location: "NTT, Indonesia",
        duration: "4 Days",
        rating: 4.8,
        reviews: 64,
        price: 7200000,
        image: "https://images.unsplash.com/photo-1578922746465-3a80a228f223?w=800&q=80",
        gallery: ["https://images.unsplash.com/photo-1578922746465-3a80a228f223?w=800&q=80"],
        category: "Adventure",
        badge: "New",
        includes: ["Liveaboard", "Semua Makan", "Dive/Snorkel", "Guide", "Tiket NP"],
        maxPax: 10,
        minAge: 12,
        description: "Petualangan melihat Komodo dragon langsung di habitat aslinya, snorkeling di Pink Beach yang memukau, dan diving kelas dunia.",
        itinerary: [
            { day: 1, title: "Labuan Bajo & Boarding", description: "Tiba Labuan Bajo, boarding liveaboard, sunset cruise." },
            { day: 2, title: "Komodo & Rinca Island", description: "Trekking lihat komodo, snorkeling Manta Point." },
            { day: 3, title: "Pink Beach & Padar", description: "Pink Beach snorkeling, trekking Padar Island sunrise." },
            { day: 4, title: "Kanawa & Kembali", description: "Snorkeling Kanawa Island, kembali ke Labuan Bajo." },
        ],
        island: "NTT",
    },
    {
        id: 6,
        slug: "lombok-gili-islands",
        title: "Lombok & Gili Islands",
        location: "NTB, Indonesia",
        duration: "5 Days",
        rating: 4.7,
        reviews: 112,
        price: 4800000,
        image: "https://images.unsplash.com/photo-1518509562904-e7ef99cdcc86?w=800&q=80",
        gallery: ["https://images.unsplash.com/photo-1518509562904-e7ef99cdcc86?w=800&q=80"],
        category: "Beach",
        badge: "Hot Deal",
        includes: ["Hotel", "Semua Makan", "Fast Boat", "Snorkeling", "Guide"],
        maxPax: 15,
        minAge: 5,
        description: "Lombok dan Gili Islands — perpaduan sempurna pantai pasir putih, snorkeling, dan budaya Sasak yang autentik.",
        itinerary: [
            { day: 1, title: "Tiba Lombok & Mandalika", description: "Check-in resort Mandalika, pantai Kuta Lombok." },
            { day: 2, title: "Gili Trawangan", description: "Fast boat ke Gili T, snorkeling, sunset swing." },
            { day: 3, title: "Gili Meno & Air", description: "Hopping 3 Gili, snorkeling bersama penyu." },
            { day: 4, title: "Rinjani Foothill", description: "Trekking ringan ke air terjun Sendang Gile." },
            { day: 5, title: "Sasak Village & Pulang", description: "Desa Sade, tenun tradisional, transfer bandara." },
        ],
        island: "NTB",
    },
];

export const destinations: Destination[] = [
    { id: 1, name: "Bali", country: "Indonesia", island: "Bali", tours: 48, image: "https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=600&q=80", description: "Pulau Dewata dengan budaya unik dan alam memukau" },
    { id: 2, name: "Raja Ampat", country: "Papua Barat, Indonesia", island: "Papua", tours: 15, image: "https://images.unsplash.com/photo-1596402184320-417e7178b2cd?w=600&q=80", description: "Keajaiban bawah laut terbaik dunia" },
    { id: 3, name: "Yogyakarta", country: "Java, Indonesia", island: "Jawa", tours: 32, image: "https://images.unsplash.com/photo-1584810359583-96fc3448beaa?w=600&q=80", description: "Pusat kebudayaan Jawa dengan warisan UNESCO" },
    { id: 4, name: "Komodo", country: "NTT, Indonesia", island: "NTT", tours: 12, image: "https://images.unsplash.com/photo-1578922746465-3a80a228f223?w=600&q=80", description: "Rumah naga Komodo dan perairan kristal" },
    { id: 5, name: "Labuan Bajo", country: "NTT, Indonesia", island: "NTT", tours: 18, image: "https://images.unsplash.com/photo-1516690561799-46d8f74f9abf?w=600&q=80", description: "Gerbang menuju kepulauan Komodo yang eksotis" },
    { id: 6, name: "Mount Bromo", country: "Jawa Timur, Indonesia", island: "Jawa", tours: 25, image: "https://images.unsplash.com/photo-1622185135505-2d795003994a?w=600&q=80", description: "Gunung api aktif dengan sunrise spektakuler" },
];

export const testimonials: Testimonial[] = [
    { id: 1, name: "Ahmad Rasyid", from: "Makassar", rating: 5, text: "Pengalaman yang luar biasa! Raja Ampat benar-benar surga tersembunyi Indonesia. Pelayanan Senja Wisata top banget.", tour: "Raja Ampat Paradise", avatar: "https://randomuser.me/api/portraits/men/22.jpg" },
    { id: 2, name: "Sari Dewi", from: "Surabaya", rating: 5, text: "Worth every penny! Tim guide sangat profesional dan pengalaman snorkeling di sana tidak ada bandingannya. Pasti balik lagi!", tour: "Bali Complete Experience", avatar: "https://randomuser.me/api/portraits/women/33.jpg" },
    { id: 3, name: "Doni Kurniawan", from: "Bandung", rating: 4, text: "Sangat puas dengan pelayanannya. Guide sangat cekatan mengatur itinerary alternatif saat cuaca kurang mendukung.", tour: "Bromo Sunrise Trekking", avatar: "https://randomuser.me/api/portraits/men/41.jpg" },
];

export const stats = [
    { value: 120, suffix: "+", label: "Destinasi" },
    { value: 500, suffix: "+", label: "Paket Wisata" },
    { value: 15000, suffix: "+", label: "Happy Travelers" },
    { value: 4.9, suffix: "★", label: "Rating Rata-rata", decimal: true },
];

export const categories = [
    { id: "beach", label: "🏖️ Pantai", icon: "🏖️" },
    { id: "culture", label: "🏛️ Budaya", icon: "🏛️" },
    { id: "adventure", label: "🧗 Petualangan", icon: "🧗" },
    { id: "family", label: "👨‍👩‍👧 Keluarga", icon: "👨‍👩‍👧" },
    { id: "honeymoon", label: "💑 Honeymoon", icon: "💑" },
];
